language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t manindra23/docker-react -f Dockerfile.dev .

script:
    - docker run manindra23/docker-react npm run test -- -- coverage